[index_config]
# TODO: once we have cname for ktra
remote_url = "https://github.com/mscott5861/crates.git"
https_username = "YOUR_USERNAME"
https_password = "GITHUB_ACCESS_TOKEN" 
branch = "master"

[server_config]
address = [127, 0, 0, 1]
port = 8000
