[index_config]
# TODO: once we have cname for ktra
remote_url = "https://bitbucket.nab.blueclouds.io/scm/nrr/rust-utoipa-struct-generator.git"
https_username = "YOUR_USERNAME"
https_password = "GITHUB_ACCESS_TOKEN" 
branch = "master"

[server_config]
address = [127, 0, 0, 1]
port = 8912
